Add button for selecting all files in the room As above ^
RealDolos/volascripts pull request #3
Opened 2018-10-26 21:07 UTC by Szero

2018-10-26 21:15 UTC, RealDolos requested changes
>unrelated formatting changes
>bad ones

b-bls

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +    } else {
>same line else
kys

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +  const style = $e("style", {
bls

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +    const {
double bls

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +        } catch (ex) {
>same line catch
KYS

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +    } finally {
m(

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +            } else {
m(

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +          } else {
🇵🇱

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +      } catch (ex) {
🇵🇱

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +              } else {
👳🏿

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +    } catch (ex) {
🙆🏽‍♂️

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +      } finally {
🤦🏻‍♀️

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +      } catch (ex) {
🤦🏻‍♀️

2018-10-26 21:15 UTC, RealDolos commented on admin.iptools.user.js
> +    fields: [{
🙆🏽‍♂️

2018-10-26 21:19 UTC, Szero commented
omg i run eslint on this without confile

2018-10-30 07:06 UTC, Szero commented
I also realized, that `git revert` doesn't revert TO the given commit, it reverts the given commits so i should revert the only this https://github.com/RealDolos/volascripts/pull/3/commits/d8fba87c9431cd72958177d6da3f5fe9c8487a48 commit, merge tool hodge-podged it together somehow tho.

2018-10-30 07:37 UTC, RealDolos requested changes

2018-10-30 07:37 UTC, RealDolos commented on admin.iptools.user.js
> +        file.dom.controlElement.firstChild.click()
>no semicolon

2018-10-30 07:37 UTC, RealDolos commented on admin.iptools.user.js
> +      if (!file.dom.fileElement.classList.contains("file_selected")) {
test for `file.getData("checked")`;

2018-10-30 07:37 UTC, RealDolos commented on admin.iptools.user.js
> +        file.dom.controlElement.firstChild.click()
`file.setData("checked", true)` should work betterly actually...
No need to check if it's checked at all.

2018-10-30 07:37 UTC, RealDolos commented on admin.iptools.user.js
> +      if (!file.dom.fileElement.classList.contains("file_selected")) {
Actually see below...

2018-10-30 07:56 UTC, Szero commented on admin.iptools.user.js
> +      if (!file.dom.fileElement.classList.contains("file_selected")) {
Above akshually

2018-10-30 08:07 UTC, merged