Add Vola Tab Report Binder script
RealDolos/volascripts pull request #7
Opened 2019-01-05 19:39 UTC by szero

When you have report tab bound to a given room and lain decides to
nuke your connection, the report tab will be bound to a random room
you have currently open, that regains connection first. This script
will bind the report room to one of your choosing by typing `/bindreports`
command in chat. The report room will be set even after browser reconnect.

2019-01-08 17:32 UTC, RealDolos requested changes
file name: admin.reportsbinder.user.js or something plox

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +  });
I cri

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +  const bindtab = "bindmehere";
I cri moar

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +  const ci = document.getElementById("chat_input");
AND MOAR!

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +      let tabbind = localStorage.getItem(bindtab);
calling localstorage.getItem a lot of times, like a pleb... tsk

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +      localStorage.setItem(bindtab, window.location.href);
why not use the actual roomid?

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +        if (message[0].hasOwnProperty("value")) {
two ifs---nested, tsk

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +        if (message[0].hasOwnProperty("value")) {
not returning early... tsk

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +          let match = message[0].value.match(`${dry.exts.user.info.nick} joined`);
uh, uwutm8

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +            ci.value = "/reports";
see above

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +          if (!!match && !!dry.exts.user.info.staff) {
.staff? not .admin? why at all?!

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +      if ("Log" === nick && tabbind === window.location.href) {
ROOMIDDDDDDD

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +      ci.value = "/reports";
herro, let's duplicate codez!

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +      dry.appendMessage("Binder", "Reports are bound to this tab now");
no, they are not. They are bound to this location

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +});
>missing newline

2019-01-08 17:32 UTC, RealDolos commented on volatabreportbinder.user.js
> +        }
herro, imma bracket pyramid!

2019-01-12 02:13 UTC, szero commented
Review changes did't auto-address themselves on push because I changed the filename, lul.

2021-03-29 19:12 UTC, merged