Add ownerhover script
RealDolos/volascripts pull request #9
Opened 2019-01-20 09:40 UTC by szero

As requested by Liquid

2019-02-08 00:34 UTC, szero commented
now with janitors support

2019-02-10 23:19 UTC, RealDolos requested changes
The entire logic is duplicated a bunch of times (and incorrect as sometimes it will only consider the room owner).
Just have some variables tracking owner and janitors, and one function to actually set/update .title according to that.
I also do not like that you capitalize names, tbh. this is imo less correct than just keeping the lower-case stuff. If you really wanted to look up the current casing of a name, there would be ways, but that's trading a lot of overhead for limited utility.

2019-02-10 23:19 UTC, RealDolos commented on titlehover.user.js
> +// @require      https://cdn.jsdelivr.net/gh/volafiled/volascripts/dry.js
require specific commit of dry.js, not master.

2019-02-10 23:19 UTC, RealDolos commented on titlehover.user.js
> +    return this[0].toUpperCase() + this.slice(1).toLowerCase();
No prototype expansion of built-in objects pls.

2019-02-10 23:19 UTC, RealDolos commented on titlehover.user.js
> +  let jannies = new Array();
[]

2019-02-10 23:19 UTC, RealDolos commented on titlehover.user.js
> +  dry.exts.connection.once("config", cfg => {
shouldn't this calculate janitors too?

2019-02-11 02:19 UTC, szero commented on titlehover.user.js
> +  dry.exts.connection.once("config", cfg => {
its the only listener naow

2019-02-11 10:49 UTC, RealDolos requested changes
Also, titlehover is  a shit file name, and the name and description aren't great either.
Also it's not "jannies"".

You only ever do stuff onload. Is that actually early enough to get the initial config always? IIRC the connect setup starts ondom so before onload and could in theory finish before onload.

2019-02-11 11:32 UTC, szero commented
I can't use extensions when I want to do stuff on dom load because they're not available yet, I could set some setInterval thing with low timeout that waits until exts is not null, but the on load listener works reliably enough.

2019-02-11 11:42 UTC, szero commented
If it's not "jannies" than what is it? What is plural form of "janny"?

2019-02-19 14:32 UTC, RealDolos commented
As already pointed out, the logic for per-user select is broken, looking at `e.target` indiscriminately, therefore breaking when the wrong element within a file element is clicked.

2019-04-23 19:05 UTC, merged